### ISSUE TITLE
Ubuntu 20.04 LTS support

### ISSUE THREAD

**Issue by Timple** [QuanergySystems/quanergy_client#19]
Currently the build fails. We have a workaround in place but it would be nice if this is supported out-of-the-box.

**Comment by rossctaylor** [comment]
@Timple - If you've got a workaround that doesn't break support for other OSs, could you submit a PR for it? Otherwise, I will definitely get 20.04 support on the todo list.

**Comment by Timple** [comment]
Nope sorry, please disregard my comment about the workaround. I was mixing up with another ROS packages which had an SDK. So no workaround for this yet.

**Comment by rossctaylor** [comment]
No worries...looks like a pretty straightforward fix.

**Comment by rossctaylor** [comment]
@Timple - See https://github.com/QuanergySystems/quanergy_client/tree/feature/add-ubuntu-focal-support

I'll need a bit longer to properly test and add instructions but this should build on 20.04 using the 18.04 instructions.

**Comment by Timple** [comment]
Thanks for being responsive! Seems to work compilation wise. Haven't had a time to test yet.

**Comment by rossctaylor** [comment]
PR merged with fixes and new instructions
